name: music_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  just_audio: ^0.9.44
  rxdart: ^0.28.0
  audio_video_progress_bar: ^2.0.3
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/songs.json
    - assets/itunes.png
    - assets/avatar.png
    - assets/google.png
